.include <../config.mk>

all:

install:
	install -d ${HELP_DIR}
	install -m 644 FAQ.html MANUAL.html README.cookie \
	README.dict README.func README.img README.m17n README.mouse \
	README.passwd README.pre_form README.tab STORY.html \
	keymap.default keymap.lynx keys-lynx.html keys-w3m.html \
	menu.default menu.submenu ${HELP_DIR}

clean:
